"""`forge new-entity NAME --fields=...` — add a CRUD entity to an existing project.

Writes a ``domain/<name>.yaml`` entity spec at the project root (creating
the ``domain/`` directory if absent) and invokes the codegen pipeline so
per-backend models + the OpenAPI bundle are refreshed immediately.

Syntax:

    forge new-entity Order --fields name:string,qty:integer,status:enum:OrderStatus

Field syntax:

    <name>:<type>[:<enum_name>][?]        # `?` suffix = optional

Supported types match the domain DSL (string, integer, number, boolean,
uuid, datetime, date, json, enum). Array / relation fields have to be
hand-edited after the initial scaffold.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

from forge.errors import GeneratorError


def _dispatch_new_entity(args) -> None:
    name = getattr(args, "new_entity_name", None)
    fields_raw = getattr(args, "new_entity_fields", None)
    project_path = Path(getattr(args, "project_path", ".")).resolve()

    if not name:
        print("error: --new-entity-name is required", file=sys.stderr)
        sys.exit(2)
    if not fields_raw:
        print(
            "error: --new-entity-fields is required (e.g. 'name:string,qty:integer')",
            file=sys.stderr,
        )
        sys.exit(2)

    try:
        body = build_entity_yaml(name, fields_raw)
    except GeneratorError as e:
        print(f"error: {e}", file=sys.stderr)
        sys.exit(2)

    domain_dir = project_path / "domain"
    domain_dir.mkdir(exist_ok=True)
    target = domain_dir / f"{_snake_case(name)}.yaml"
    if target.exists():
        print(
            f"error: {target} already exists. Edit it directly or delete it first.", file=sys.stderr
        )
        sys.exit(2)

    target.write_text(body, encoding="utf-8")
    print(f"Wrote {target.relative_to(project_path)}")
    print("Run `forge --update` (or regenerate) to pick up the new entity.")
    sys.exit(0)


def build_entity_yaml(name: str, fields_spec: str) -> str:
    """Produce a minimal, valid entity YAML body.

    Every entity gets the CRUD baseline (id, customer_id, user_id, timestamps)
    plus the user-declared fields. Indices default to ``(customer_id, name)``
    when a ``name`` field is present.
    """
    parsed_fields = parse_field_spec(fields_spec)

    has_name = any(f["name"] == "name" for f in parsed_fields)

    fields: list[dict] = []
    fields.append({"name": "id", "type": "uuid", "primary_key": True})
    for f in parsed_fields:
        fields.append(f)
    fields.append({"name": "customer_id", "type": "uuid"})
    fields.append({"name": "user_id", "type": "uuid"})
    fields.append({"name": "created_at", "type": "datetime"})
    fields.append({"name": "updated_at", "type": "datetime"})

    body: dict = {
        "name": name,
        "plural": _plural(_snake_case(name)),
        "description": f"{name} — CRUD entity (generated by forge new-entity).",
        "fields": fields,
    }
    if has_name:
        body["indices"] = [["customer_id", "name"]]

    return yaml.safe_dump(body, sort_keys=False, default_flow_style=False)


def parse_field_spec(raw: str) -> list[dict]:
    """Parse the ``name:type[:enum][?]`` comma-separated field list."""
    fields: list[dict] = []
    for entry in raw.split(","):
        entry = entry.strip()
        if not entry:
            continue
        optional = entry.endswith("?")
        if optional:
            entry = entry[:-1]
        parts = entry.split(":")
        if len(parts) < 2:
            raise GeneratorError(f"field {entry!r}: expected '<name>:<type>[:<enum>]'")
        name, type_ = parts[0].strip(), parts[1].strip()
        if not name:
            raise GeneratorError(f"field spec missing name in entry {entry!r}")
        field: dict = {"name": name, "type": type_}
        if optional:
            field["optional"] = True
        if type_ == "enum":
            if len(parts) < 3 or not parts[2]:
                raise GeneratorError(f"field {name!r} (type=enum) needs an enum name")
            field["enum"] = parts[2].strip()
        fields.append(field)
    return fields


def _snake_case(name: str) -> str:
    out: list[str] = []
    for i, c in enumerate(name):
        if c.isupper() and i > 0 and not name[i - 1].isupper():
            out.append("_")
        out.append(c.lower())
    return "".join(out)


def _plural(snake: str) -> str:
    """Naive English pluralization — `item` → `items`, `policy` → `policies`."""
    if snake.endswith("y") and len(snake) > 1 and snake[-2] not in "aeiou":
        return snake[:-1] + "ies"
    if snake.endswith(("s", "x", "z", "ch", "sh")):
        return snake + "es"
    return snake + "s"
