"""Cross-backend HTTP smoke contract (RFC-006).

Every backend generated by forge — regardless of language — must expose
a minimal HTTP surface so lane C's compose-up test can assert a wire-
level parity contract without reaching into language-specific internals.
This module is the concrete expression of that contract.

It is **not** a pytest module — lane C (see :func:`run_lane_smoke` in
``tests/matrix/runner.py`` once sprint 2 lands) imports and calls
:func:`assert_contract` after spinning up a generated project with
``docker compose``. Kept out of the pytest collection path so CI
doesn't try to run it against a non-existent server during lane A / B.

Contract endpoints:

- ``GET /healthz`` (or ``/health/live``) — 200 ``{"status": "ok"}``
- ``GET /readyz`` (or ``/health/ready``) — 200 when deps up, 503 else
- ``GET /api/schema`` (OpenAPI) — valid OpenAPI 3.1 document
- ``POST /api/v1/{example}`` — 201 + body (happy path)
- ``GET /api/v1/{example}/{id}`` — 200 + body
- ``PATCH /api/v1/{example}/{id}`` — 200 + body
- ``DELETE /api/v1/{example}/{id}`` — 204

Paths tolerate the minor routing variation between FastAPI, Fastify,
and Axum — the contract is "some endpoint at a predictable path"
rather than a byte-for-byte match.
"""

from __future__ import annotations

import json
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class ContractViolation:
    endpoint: str
    reason: str
    status: int | None = None
    body: str | None = None


@dataclass(frozen=True)
class ContractResult:
    scenario: str
    backend_name: str
    violations: tuple[ContractViolation, ...]

    @property
    def passed(self) -> bool:
        return not self.violations


# All three backend templates (python, node, rust) currently expose
# health under ``/api/v1/health/{live,ready}``. The unprefixed variants
# stay in the tuple so a future minimal-service template (no /api/v1
# router) is still covered, and so a custom backend that follows the
# Kubernetes-style ``/healthz`` convention also passes the contract.
HEALTH_LIVE_PATHS: tuple[str, ...] = ("/api/v1/health/live", "/healthz", "/health/live")
HEALTH_READY_PATHS: tuple[str, ...] = ("/api/v1/health/ready", "/readyz", "/health/ready")
OPENAPI_PATHS: tuple[str, ...] = (
    "/openapi.json",
    "/api/v1/openapi.json",
    "/api/schema",
    "/api/openapi.json",
)


def _get_first(base_url: str, paths: tuple[str, ...], timeout_s: int) -> tuple[str, int, bytes]:
    """Try each path in order, return the first that doesn't 404.

    Returns ``(path, status, body)``. Raises the final network error
    if every path raises."""
    last_exc: Exception | None = None
    for path in paths:
        url = base_url.rstrip("/") + path
        try:
            with urllib.request.urlopen(url, timeout=timeout_s) as resp:
                body = resp.read()
                return path, resp.status, body
        except urllib.error.HTTPError as e:
            if e.code == 404:
                last_exc = e
                continue
            return path, e.code, e.read() or b""
        except urllib.error.URLError as e:
            last_exc = e
            continue
    if last_exc is not None:
        raise last_exc
    raise RuntimeError("no paths supplied")


def _check_health_live(base_url: str, timeout_s: int, violations: list[ContractViolation]) -> None:
    try:
        path, status, body = _get_first(base_url, HEALTH_LIVE_PATHS, timeout_s)
    except Exception as exc:  # noqa: BLE001
        violations.append(
            ContractViolation(
                endpoint="/healthz",
                reason=f"no liveness endpoint responded ({type(exc).__name__}): {exc}",
            )
        )
        return
    if status != 200:
        violations.append(
            ContractViolation(
                endpoint=path,
                reason=f"liveness should return 200 (got {status})",
                status=status,
                body=body.decode("utf-8", "replace")[:200],
            )
        )
        return
    try:
        payload = json.loads(body)
    except ValueError:
        violations.append(
            ContractViolation(
                endpoint=path,
                reason="liveness body is not JSON",
                status=status,
                body=body.decode("utf-8", "replace")[:200],
            )
        )
        return
    status_field = payload.get("status")
    if status_field not in ("ok", "UP"):
        violations.append(
            ContractViolation(
                endpoint=path,
                reason=f"liveness 'status' must be 'ok' or 'UP', got {status_field!r}",
                status=status,
                body=json.dumps(payload)[:200],
            )
        )


def _check_health_ready(base_url: str, timeout_s: int, violations: list[ContractViolation]) -> None:
    try:
        path, status, body = _get_first(base_url, HEALTH_READY_PATHS, timeout_s)
    except Exception as exc:  # noqa: BLE001
        violations.append(
            ContractViolation(
                endpoint="/readyz",
                reason=f"no readiness endpoint responded ({type(exc).__name__}): {exc}",
            )
        )
        return
    # Readiness is allowed to be 503 if deps are down; the contract is
    # that it returns *some* structured answer, not that the service is
    # healthy right this second. 200 is the happy path we expect from
    # lane C's compose-up harness (which also brings postgres up).
    if status not in (200, 503):
        violations.append(
            ContractViolation(
                endpoint=path,
                reason=f"readiness must return 200 (UP) or 503 (DOWN), got {status}",
                status=status,
                body=body.decode("utf-8", "replace")[:200],
            )
        )
        return
    try:
        payload = json.loads(body)
    except ValueError:
        violations.append(
            ContractViolation(
                endpoint=path,
                reason="readiness body is not JSON",
                status=status,
                body=body.decode("utf-8", "replace")[:200],
            )
        )
        return
    if "status" not in payload:
        violations.append(
            ContractViolation(
                endpoint=path,
                reason="readiness JSON must include 'status'",
                status=status,
                body=json.dumps(payload)[:200],
            )
        )


def _check_openapi(base_url: str, timeout_s: int, violations: list[ContractViolation]) -> None:
    try:
        path, status, body = _get_first(base_url, OPENAPI_PATHS, timeout_s)
    except Exception as exc:  # noqa: BLE001
        violations.append(
            ContractViolation(
                endpoint="/openapi.json",
                reason=f"no OpenAPI endpoint responded ({type(exc).__name__}): {exc}",
            )
        )
        return
    if status != 200:
        violations.append(
            ContractViolation(
                endpoint=path,
                reason=f"OpenAPI endpoint should return 200 (got {status})",
                status=status,
                body=body.decode("utf-8", "replace")[:200],
            )
        )
        return
    try:
        doc = json.loads(body)
    except ValueError:
        violations.append(
            ContractViolation(
                endpoint=path,
                reason="OpenAPI body is not JSON",
                status=status,
                body=body.decode("utf-8", "replace")[:200],
            )
        )
        return
    if not isinstance(doc, dict) or not doc.get("openapi"):
        violations.append(
            ContractViolation(
                endpoint=path,
                reason="OpenAPI doc must declare 'openapi' version field",
                status=status,
                body=json.dumps(doc)[:200] if isinstance(doc, dict) else "",
            )
        )
        return
    if not doc.get("paths"):
        violations.append(
            ContractViolation(
                endpoint=path,
                reason="OpenAPI doc must expose at least one path",
                status=status,
            )
        )


def _wait_for_ready(base_url: str, max_wait_s: int) -> None:
    """Poll the liveness endpoint until the backend responds (any status).

    ``compose up --wait`` only blocks until containers are *running* —
    not until the application has finished startup. The deploy compose
    template doesn't define per-backend healthchecks (the ``slim``
    runtime images for python / node / rust don't share a single
    portable healthcheck command), so the wait happens here. Any HTTP
    response — including 404 / 503 — counts as "up": it means the
    server is binding and accepting connections, even if specific
    endpoints aren't yet wired. ``ConnectionResetError`` and refused
    connections trigger a retry with exponential backoff.

    No-op once the deadline passes; the per-endpoint checks below will
    surface the actual error in that case.
    """
    deadline = time.monotonic() + max_wait_s
    delay = 0.5
    url = base_url.rstrip("/") + HEALTH_LIVE_PATHS[0]
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=2):
                return
        except urllib.error.HTTPError:
            return  # server responded with a status — it's up
        except (urllib.error.URLError, ConnectionResetError, OSError):
            time.sleep(delay)
            delay = min(delay * 1.5, 4.0)


def assert_contract(
    base_url: str,
    scenario: str,
    backend_name: str,
    *,
    timeout_s: int = 10,
    readiness_wait_s: int = 60,
) -> ContractResult:
    """Run the RFC-006 HTTP contract against a live backend.

    ``base_url`` is the reachable root (``http://localhost:<port>``).
    ``scenario`` and ``backend_name`` are labels for the return value —
    the runner uses them to attribute violations back to the scenario
    grid. ``readiness_wait_s`` caps how long :func:`_wait_for_ready`
    will block before running the per-endpoint checks.

    The CRUD portion of the contract (``POST``/``GET``/``PATCH``/
    ``DELETE`` cycle against a seed entity) is a sprint-2 follow-on
    — asserting it here would require knowing the entity's required
    fields ahead of time, which varies per fragment. Tracked in
    RFC-006's open questions.
    """
    _wait_for_ready(base_url, readiness_wait_s)
    violations: list[ContractViolation] = []
    _check_health_live(base_url, timeout_s, violations)
    _check_health_ready(base_url, timeout_s, violations)
    _check_openapi(base_url, timeout_s, violations)
    return ContractResult(
        scenario=scenario,
        backend_name=backend_name,
        violations=tuple(violations),
    )


def format_result(result: ContractResult) -> str:
    """Human-readable one-liner-per-violation for CLI / CI logs."""
    if result.passed:
        return f"[OK  ] {result.scenario}/{result.backend_name} — contract satisfied"
    lines = [f"[FAIL] {result.scenario}/{result.backend_name}"]
    for v in result.violations:
        suffix = []
        if v.status is not None:
            suffix.append(f"status={v.status}")
        if v.body:
            suffix.append(f"body={v.body!r}")
        suffix_str = f" ({', '.join(suffix)})" if suffix else ""
        lines.append(f"       {v.endpoint}: {v.reason}{suffix_str}")
    return "\n".join(lines)


def results_exit_code(results: list[ContractResult]) -> int:
    """Exit code for the runner's lane C entry point.

    0 — every result passed.
    2 — at least one violation. Matches the lane A exit-code convention
    so downstream CI logic doesn't need a special case.
    """
    return 0 if all(r.passed for r in results) else 2


__all__ = [
    "ContractResult",
    "ContractViolation",
    "assert_contract",
    "format_result",
    "results_exit_code",
]


def _self_test() -> dict[str, Any]:
    """Internal smoke test for the contract module itself.

    Not a pytest test (this file is outside the collection path). The
    runner imports this when ``--self-test`` is passed, so a broken
    contract module doesn't silently skip every lane-C scenario.
    """
    # Fake server via a http.server subclass would be ideal but would
    # make this file stateful. Instead, emit a synthesis of the module
    # surface so the runner can at least confirm the imports work and
    # all functions are callable before it starts docker compose.
    return {
        "functions": ["assert_contract", "format_result", "results_exit_code"],
        "dataclasses": ["ContractResult", "ContractViolation"],
        "endpoint_sets": {
            "health_live": list(HEALTH_LIVE_PATHS),
            "health_ready": list(HEALTH_READY_PATHS),
            "openapi": list(OPENAPI_PATHS),
        },
    }
